### Session04 (Loop)

In [6]:
for i in range(2):
  print("python")
print("out of loop")

python
python
out of loop

In [10]:
for num in range(4):
  print(num)

0
1
2
3

In [ ]:
# range(start, stop, step)
# start ====> default : 0
# step ====> default: 1
# stop =====> xxxxxxxxx

In [14]:
for num in range(2, 7, 2): # num = 2, num = 4, num = 6
  print(num)
print("out of loop: ",num)

2
4
6
out of loop:  6

In [22]:
number = int(input("number of student: "))
for i in range(number):  # i = 0, i = 1, i = 2
  score = float(input(f"score of student_{i+1}: "))
  if score >= 10:
    print("you passed")
  else:
    print("you didn't pass")

you passed
you passed

In [24]:
num = int(input("number: "))
for i in range(num): # i = 0 .... i = 5
  if i % 3 == 0:
    print(i)

0
3

In [25]:
num = int(input("number: "))
for i in range(0, num, 3): # i = 0 .... i = 5
  print(i)

0
3

In [28]:
name = "python" # 0 ... 5
for i in range(6):
  print(name[i])

p
y
t
h
o
n

In [29]:
name = "python"
#        c
for c in name:
  print(c)

p
y
t
h
o
n

In [32]:
name = "aaabbb"
#         3
count_a = 0
for c in name:
  if c == "a":
    count_a += 1
print(count_a)

3

In [35]:
x = 10
print(x)
x += 5  # x = x + 5
print(x)

10
15

### break, continue

In [39]:
for i in range(6):
  score = input(f"score_{i+1}: ")
  if score == "exit":
    break
  print(float(score))

12.0

In [43]:
for number in range(7,10):
  print("number: ", number)

for number in range(11,14):
  print("number: ", number)

number:  7
number:  8
number:  9
number:  11
number:  12
number:  13

In [54]:
for number in range(7,14):
  print(number, end=",")
  print("python", end=",")
  if number == 8:
    continue
  print("java", end=",")
  print("c++", end=",")

7,python,java,c++,8,python,9,python,java,c++,10,python,java,c++,11,python,java,c++,12,python,java,c++,13,python,java,c++,

### Example

python
ython,
thon,
hon, p
on, py
n, pyt
, pyth
 pytho
python
ython,
thon,
hon, j
on, ja
n, jav
, java
 java,
java,
ava, c
va, c,
a, c,
, c, p
 c, py
c, pyt
, pyth
 pytho
python
ython
thon
hon
on
n

In [58]:
name = "python, python, java, c, python"
#       i=0
# substr = "python" ===> l1 = 6
# i = 0 + 6 . name [0:i]
substr = "python"
l1 = len(name)
for i in range(l1):
  if name[i:i+len(substr)] == substr:
    print(i)

0
8
25

In [ ]:
num1 = 12
max_num = num1
num2 = 13
if num2 > max_num:
  max_num = num2
num3 = 27
if num3 > max_num:
  max_num = num3
num4 = 16
if num4 > max_num:
  max_num = num4

In [63]:
score1 = float(input("your score: "))
max_score = score1
sum_score = score1
for i in range(3):
  score = float(input("score: "))
  sum_score += score
  if score > max_score:
    max_score = score
print(f"max scores: {max_score}")
avg = sum_score / 4
print(f"avg: {avg}")

max scores: 6.0
avg: 4.5

In [66]:
x = 10
print(f"result: {x}")

result: 10

In [13]:
import numpy as np
example = np.ones((6, 6, 6))
print("array:")
print(example)
example[:,:,2] = 2
print("Modified array:")
print(example)

array:
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
Modified array:
[[[1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]]

 [[1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]]

 [[1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]]

 [[1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]]

 [[1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]]

 [[1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]]]

In [14]:
x_num = 400
y_num = 150
tau = 0.54
t_number = 2500
lattice_num = 9
import numpy as np
speed_of_all_in_x_dir = np.array([0,0,1,1,1,0,-1,-1,-1])
weights = np.array([4/9,1/9,1/36,1/9,1/36,1/9,1/36])
F = np.ones((y_num, x_num, lattice_num)) + 0.001 * np.random.rand(y_num,x_num,lattice_num)
F

array([[[1.00002318, 1.00017036, 1.00072952, ..., 1.0000498 ,
         1.00008702, 1.00078688],
        [1.00074806, 1.00084694, 1.00087022, ..., 1.00027504,
         1.00080188, 1.00096936],
        [1.00020423, 1.00065003, 1.00028922, ..., 1.00021712,
         1.00039684, 1.00001126],
        ...,
        [1.00054378, 1.00003948, 1.00097402, ..., 1.0005189 ,
         1.00049758, 1.0006089 ],
        [1.00089676, 1.00001772, 1.00030628, ..., 1.00056791,
         1.00010135, 1.00033555],
        [1.00073985, 1.00034669, 1.00084594, ..., 1.00045077,
         1.00043407, 1.00057007]],

       [[1.00013101, 1.00092591, 1.00029289, ..., 1.00076699,
         1.0006904 , 1.00013047],
        [1.00002052, 1.00085082, 1.00007817, ..., 1.0004414 ,
         1.00022399, 1.00074153],
        [1.00091315, 1.00034581, 1.00075746, ..., 1.00013177,
         1.00025291, 1.00012531],
        ...,
        [1.00090386, 1.00044396, 1.00015426, ..., 1.00093854,
         1.00030006, 1.00079097],
        [1.00039217, 1.00061951, 1.00011272, ..., 1.00058865,
         1.00078695, 1.00088972],
        [1.00072453, 1.00056012, 1.00000612, ..., 1.00006255,
         1.00083268, 1.00000588]],

       [[1.00034033, 1.00065671, 1.00021682, ..., 1.00012778,
         1.00021655, 1.00001142],
        [1.00063382, 1.00050332, 1.000949  , ..., 1.00098307,
         1.00096348, 1.00042234],
        [1.00011407, 1.000478  , 1.00028642, ..., 1.00048501,
         1.00000438, 1.00045106],
        ...,
        [1.00074984, 1.00068908, 1.00031792, ..., 1.00003177,
         1.00058083, 1.00054009],
        [1.00068481, 1.00020876, 1.0007855 , ..., 1.00004592,
         1.00055712, 1.00037123],
        [1.00034078, 1.00011248, 1.0000191 , ..., 1.00084814,
         1.00033829, 1.0006425 ]],

       ...,

       [[1.00091802, 1.00046858, 1.000236  , ..., 1.00024538,
         1.0001846 , 1.00017159],
        [1.00023737, 1.0009748 , 1.00090366, ..., 1.00004888,
         1.00070345, 1.00069701],
        [1.00055575, 1.00004692, 1.00016606, ..., 1.00054963,
         1.0007037 , 1.00049408],
        ...,
        [1.00014993, 1.00007637, 1.00034412, ..., 1.00010978,
         1.00059937, 1.00063618],
        [1.00077212, 1.00037657, 1.00012059, ..., 1.00091296,
         1.00041998, 1.00080776],
        [1.0007624 , 1.00015584, 1.00094356, ..., 1.00004731,
         1.00008218, 1.00009993]],

       [[1.0005782 , 1.00029572, 1.00014233, ..., 1.00097319,
         1.00070105, 1.00087342],
        [1.00006263, 1.00096336, 1.00006263, ..., 1.00078306,
         1.0003385 , 1.00084233],
        [1.00044446, 1.00008985, 1.00097823, ..., 1.00068382,
         1.00024213, 1.00000351],
        ...,
        [1.00028465, 1.00000429, 1.0005547 , ..., 1.0004938 ,
         1.00090428, 1.00060889],
        [1.00070486, 1.00060098, 1.00016081, ..., 1.00009803,
         1.00036402, 1.00059916],
        [1.0008061 , 1.00046124, 1.0004306 , ..., 1.00091487,
         1.00039414, 1.00097588]],

       [[1.00042393, 1.00032684, 1.00095809, ..., 1.00058934,
         1.0005972 , 1.00053456],
        [1.00021687, 1.00050528, 1.00003137, ..., 1.00006357,
         1.00079833, 1.00019552],
        [1.0002842 , 1.00025282, 1.00045944, ..., 1.00067636,
         1.00066942, 1.00066215],
        ...,
        [1.00043064, 1.00073144, 1.00052024, ..., 1.00037901,
         1.0007511 , 1.00005215],
        [1.00005174, 1.00090073, 1.00089478, ..., 1.00022199,
         1.00099028, 1.00087409],
        [1.0002049 , 1.0008392 , 1.00047451, ..., 1.00060282,
         1.00022072, 1.00058533]]])

In [15]:
F.shape

(150, 400, 9)

In [26]:
F[:,:,3] = 2

In [30]:
F[0][0].shape

(9,)

In [21]:
F[0,:,3]

array([1.00068543, 1.00041296, 1.00076767, 1.00071102, 1.00045961,
       1.000461  , 1.00050312, 1.0002757 , 1.00057294, 1.00063544,
       1.00034882, 1.00098969, 1.00075311, 1.00066124, 1.00009559,
       1.00000179, 1.00026625, 1.00023781, 1.00026213, 1.00002824,
       1.00049364, 1.00047865, 1.00062179, 1.00092535, 1.0008419 ,
       1.00010521, 1.0004055 , 1.00054586, 1.00019381, 1.00012226,
       1.00068372, 1.0003834 , 1.00085818, 1.00022935, 1.00058386,
       1.00096972, 1.00051262, 1.00003933, 1.00070253, 1.00048455,
       1.00073179, 1.00096562, 1.00000248, 1.00077483, 1.00047741,
       1.00081928, 1.00061103, 1.00060558, 1.00009394, 1.00018224,
       1.00088779, 1.00088933, 1.00046597, 1.00054989, 1.000734  ,
       1.00007389, 1.00035961, 1.00060784, 1.0004698 , 1.00094615,
       1.00064384, 1.00067654, 1.00004938, 1.00030471, 1.00063888,
       1.0003499 , 1.00099235, 1.00060864, 1.00054455, 1.00069251,
       1.0009476 , 1.00024241, 1.00092684, 1.00058734, 1.00024045,
       1.0000296 , 1.00071347, 1.00073449, 1.00050713, 1.00091562,
       1.00007789, 1.00007267, 1.00014113, 1.00079143, 1.00085204,
       1.00035304, 1.00062205, 1.00005021, 1.0007215 , 1.00082152,
       1.00070128, 1.00061833, 1.00045553, 1.00012406, 1.00012386,
       1.00000174, 1.00044004, 1.00044724, 1.00094469, 1.00059729,
       1.00029273, 1.00078461, 1.0007799 , 1.00026302, 1.00069542,
       1.00035635, 1.00023335, 1.00084442, 1.00017905, 1.00095416,
       1.000353  , 1.00083889, 1.00010381, 1.00041372, 1.0001004 ,
       1.00080278, 1.00046502, 1.00012096, 1.00016676, 1.00057804,
       1.00081703, 1.00072924, 1.00077402, 1.00037372, 1.00036444,
       1.00064747, 1.00088878, 1.00082489, 1.00080733, 1.00090522,
       1.00051013, 1.00019425, 1.00026125, 1.00000598, 1.00093453,
       1.00065856, 1.00070653, 1.00076523, 1.0009221 , 1.00024185,
       1.00040075, 1.00086631, 1.00035446, 1.00033618, 1.00091159,
       1.00003993, 1.00030492, 1.00070886, 1.00041147, 1.00019975,
       1.0004918 , 1.00028706, 1.00045341, 1.00028472, 1.00032422,
       1.00076938, 1.00046507, 1.00060324, 1.00069393, 1.00082739,
       1.00076787, 1.00099925, 1.00011819, 1.00058652, 1.00091475,
       1.00081497, 1.00098555, 1.00069204, 1.00068018, 1.00082813,
       1.00053957, 1.00030102, 1.00053775, 1.00042959, 1.00099288,
       1.00015713, 1.00050267, 1.00077857, 1.00073138, 1.00066089,
       1.00065898, 1.00080882, 1.00022635, 1.00039975, 1.00082782,
       1.00022267, 1.00016807, 1.0003073 , 1.00084528, 1.00035063,
       1.00087376, 1.00073597, 1.00078156, 1.00068687, 1.00049698,
       1.00074595, 1.00070797, 1.00003765, 1.00046004, 1.00004701,
       1.00017041, 1.00096289, 1.00048161, 1.00051198, 1.00003601,
       1.00083032, 1.00059946, 1.00018578, 1.00090315, 1.0004713 ,
       1.00091576, 1.00011632, 1.00003124, 1.00070958, 1.00039389,
       1.00017533, 1.00072046, 1.00067101, 1.00070686, 1.00015127,
       1.00063629, 1.00028183, 1.00075454, 1.00083026, 1.00018833,
       1.00014156, 1.00067691, 1.00082996, 1.00038526, 1.00093797,
       1.00014311, 1.00011493, 1.00078389, 1.00002966, 1.00005801,
       1.00043587, 1.00031468, 1.00058951, 1.00029967, 1.00015341,
       1.00034325, 1.0007054 , 1.00035036, 1.00035866, 1.00062587,
       1.00013451, 1.00010857, 1.00051455, 1.00097346, 1.00061434,
       1.00083061, 1.00017669, 1.00058459, 1.00045572, 1.00006977,
       1.00033863, 1.00060009, 1.00084785, 1.00052619, 1.0008291 ,
       1.00023238, 1.0009555 , 1.00086356, 1.00036371, 1.00087499,
       1.00037016, 1.00054608, 1.00009566, 1.00029597, 1.00007907,
       1.00010839, 1.00094875, 1.00009431, 1.0006741 , 1.00060725,
       1.00039416, 1.00029644, 1.0006847 , 1.00067593, 1.00001725,
       1.00046316, 1.00004065, 1.00043362, 1.00023141, 1.00078163,
       1.00029259, 1.00099447, 1.00034144, 1.00027014, 1.00080689,
       1.00048106, 1.00002626, 1.00047988, 1.00050779, 1.00084478,
       1.00044767, 1.00013111, 1.00084114, 1.0007837 , 1.00008723,
       1.00010559, 1.00025023, 1.00090621, 1.00047496, 1.0008697 ,
       1.00002972, 1.00067509, 1.00051906, 1.00020934, 1.00012597,
       1.00063109, 1.00065014, 1.00061597, 1.00024667, 1.00058484,
       1.00027387, 1.00005649, 1.00048764, 1.00035926, 1.00020756,
       1.00079856, 1.00069302, 1.00011597, 1.00033847, 1.00040391,
       1.00030579, 1.00061863, 1.00034022, 1.00015324, 1.0006587 ,
       1.0007696 , 1.00036038, 1.00010972, 1.00034626, 1.00014868,
       1.0006475 , 1.00005781, 1.00021058, 1.0003172 , 1.00093619,
       1.00046627, 1.00033631, 1.00024508, 1.00096984, 1.00024904,
       1.00029953, 1.00024721, 1.00063838, 1.00033093, 1.00072414,
       1.00069207, 1.00006464, 1.00050687, 1.00007259, 1.00059776,
       1.00038929, 1.00060316, 1.00085007, 1.00095591, 1.000679  ,
       1.00002757, 1.00068415, 1.00038738, 1.0000693 , 1.00038383,
       1.00080954, 1.00077576, 1.00050062, 1.00084278, 1.00006297,
       1.00023588, 1.00095099, 1.00041128, 1.00014065, 1.00077638,
       1.00091009, 1.00034303, 1.000258  , 1.00011896, 1.00046433,
       1.0001504 , 1.00004226, 1.00029977, 1.00053362, 1.00061218,
       1.00056462, 1.00079195, 1.00062567, 1.00023463, 1.00031589,
       1.00080495, 1.00013669, 1.00058831, 1.00029097, 1.00038691,
       1.00077302, 1.00042009, 1.00012071, 1.00009767, 1.00074886])